name: Generate changelog
inputs:
  prompt-file:
    type: string
    default: "internal-changelog-prompt.md"
  base-ref:
    type: string
    required: true
  head-ref:
    type: string
    required: true
outputs:
  changelog:
    value: ${{steps.generate.outputs.changelog}}
runs:
  using: "composite"
  steps:
    - name: Generate changelog
      id: generate
      shell: bash
      run: |
        EOF1=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        EOF2=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        cat << $EOF1 >> $GITHUB_OUTPUT
        changelog<<$EOF2
        $(uv run generate_changelog.py -p ${{inputs.prompt-file}} ${{inputs.base-ref}} ${{inputs.head-ref}})
        $EOF2
        $EOF1
