name: Generate changelog
inputs:
  preset-prompt:
    type: string
    default: internal
  prompt-file:
    type: string
  base-ref:
    type: string
    required: true
  head-ref:
    type: string
    required: true
outputs:
  changelog:
    value: ${{steps.generate.outputs.changelog}}
runs:
  using: "composite"
  steps:
    - name: Install UV
      uses: astral-sh/setup-uv@v6
    - name: Generate changelog
      id: generate
      shell: bash
      run: |
        if [ -n "${{inputs.prompt-file}}" ]; then
          content=$(<"${{inputs.prompt-file}}")
        else
          content=$(<"${{github.action_path}}/prompts/${{inputs.prompt-preset}}.md")
        fi
        EOF1=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        EOF2=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        cat << $EOF1 >> $GITHUB_OUTPUT
        changelog<<$EOF2
        $(uv run ${{github.action_path}}/generate_changelog.py -p ${{inputs.prompt-file}} ${{inputs.base-ref}} ${{inputs.head-ref}})
        $EOF2
        $EOF1
